apt.sh
In some cases apt.sh could output duplicated arch values causing the
following error:
Aug 29 12:12:22 host123 prometheus-node-exporter[2235]: time="2019-08-29T12:12:22Z" level=error msg="error gathering metrics: [from Gatherer #2] collected metric \"apt_upgrades_pending\" { label:<name:\"arch\" value:\"Debian/Ubuntu\" > label:<name:\"origin\" value:\"PostgreSQLfor\" > gauge:<value:6 > } was collected before with the same name and label values\n" source="log.go:172"
Signed-off-by: Andrey Arapov <andrey.arapov@nixaid.com>
=> Fix apt.sh arch duplication (#7)

apt.sh
=> apt.sh: use "dist-upgrade" instead of "upgrade" to include all updates

smartmon.sh
smartctl can deal with NVMes (at least in newer versions) and return
some data. When encountering an unknown disk type, don't print to
stdout, as this will break the node exporter. Print the error message to
stderr.
I re-submitted this per https://github.com/prometheus/node_exporter/pull/1313, as I'm still affected by the bug.
=> smartmon.sh: don't fail on nvme, don't print error to metrics.

smartmon.py
At least on Hitachi hard disks the value of the Temperature_Celsius
attribute is not useful to the system administrator. It is the raw
value that actually contains the temperature in celsius.
Signed-off-by: Timo Juhani Lindfors <timo.lindfors@iki.fi>
=> Collect raw SMART values

storcli.py
Helpful for detecting whether a drive has been unplugged and put back in, or replaced with a different drive.
Signed-off-by: Brian Candler <b.candler@pobox.com>
=> Include drive serial number as label in megaraid_pd_info

yum.sh
* Change "yum check-updates" to "yum check-update" to work with CentOS 6+
* Allow - and + in package names; simplify awk pipeline
Fixes #14
=> yum.sh fixes

yum.sh
Break up the long pipeline in the yum.sh script to make it easier to
read.
Add bash sanity settings.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Split up yum.sh script long line

yum.sh
When yum output is redirected, it wraps to 80 columns (https://bugzilla.redhat.com/show_bug.cgi?id=584525) - for long lines, this results in yum_upgrades_pending metrics with origin="".
Adding xargs to the pipeline corrects things so awk works as intended.
Signed-off-by: Ben Ritcey <ben+github@ritcey.com>
=> have yum.sh deal with long lines from yum

smartmon.py
Pull request contains a few fixes:
* A previous change introduced a regression and cause a few SMART tests to fail. (namely device_is_active) This is fixed by allowing `smart_ctl` to fail again and opt out of error checks explicitly. 
* Small fix that caused python to interpret `\d` as en escape sequence.
* Add a `--wakeup-disks` command line argument to optionally wake up disks and query them for their SMART values.
* deduplicate SMART attributes when reporting them as metrics to prometheus.
The last change is the most controversial one I assume. I found a disk that reports the same attribute name under different IDs.
```
171 Program_Fail_Count      0x000a   000   000   000    Old_age   Always       -       7
181 Program_Fail_Count      0x000a   000   000   000    Old_age   Always …
```
=> Dedup attributes

nvme_metrics.sh
I guess this is a breaking change as the metric name will go from:
`temperature_celcius` to `temperature_celsius`
=> Fix typo in temperature metric (Closes #46)

nvme_metrics.sh
The `cut` command assumes that `device` is in the format `/dev/nvmeX` and will fail if the NVMe number is higher than 9 (e.g. `/dev/nvme10`).
Therefore use a built-in shell method to calculate the basename of the device. (Closes #18)
Parsing the human-readable output of nvme with awk is fragile since the output format is not promised to be stable. Therefore use the JSON output format to make the script more robust.
=> nvme_metrics.sh: Support for more than 10 NVMe and use JSON output of nvme

.flake8, tw_cli.py
Convert `tw_cli.py` textfile collector to Python 3 and address flake8 nags. Also do a few minor cleanups to docstrings, formatting, and simplify some if-statements.
Note that this script still uses `OptionParser`, which has been deprecated since Python 3.2. We could convert this to `ArgumentParser`, but this would raise our minimum supported Python version to 3.2 (which is still ancient). @SuperQ let me know if you want me to go ahead with that. The smartmon.py and storcli.py collectors already use `ArguementParser`, so one could "argue" that we already require Python 3.2 ;-)
This script still contains a few references to Nagios and associated terminology, as it was originally based on a very old Nagios plugin. Overall it could be substantially simplified and made more elegant by using …
=> Update tw_cli.py to Python 3

smartmon.py
Some device models report "---" in the threshold value where most devices would report "000".
This was crashing the program with a parse exception.
=> smartmon.py: fix parse error

mellanox_hca_temp
To be consistent with the `node_infiniband_*` labels (e.g. `node_infiniband_info`) from the Prometheus node exporter, rename the
metric label `hca_device` to `device`. Then you can write an alert to check for missing temperature metrics:
```
node_infiniband_info unless on (instance, device) node_infiniband_hca_temp_celsius
```
Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>
=> mellanox_hca_temp: Rename hca_device label to device

apt.sh
I find it useful to have a metric counting APT packages pending autoremove to keep my Debian nodes clean.
=> apt.sh: return packages pending autoremove

smartmon.py
Disk names can contain quotes, e.g. in "Toshiba 2.5" HDD MK..52GSX".
=> smartmon.py: Escape quotes in label values

storcli.py
When using perccli with missing Cachevault_Info the script is interrupted on an early stage. This PR is to ignore missing key and continue processing.
=> Do not interrupt processing if Cachevault_Info is missing

btrfs_stats.py
The `line == ''` check doesn't work in Python 3, which uses bytestrings. Replace it with `not line`.
Without this change, the script can crash, since the empty line will trigger the RuntimeError on line 49.
=> btrfs_stats: detect empty lines in Python 3

node_os_info.sh
Enable older OSes, like CentOS 6 and early versions of Ubuntu 12.04, to generate `node_os_info` and `node_os_version` metrics.
See https://github.com/prometheus/node_exporter/issues/2252
=> Add node_os_info.sh collector

nvme_metrics.sh
nvme-cli v2.x and later outputs various NVMe 128-bit counters as double-quoted strings, which tripped up this script and resulted in Prometheus text metrics exposition format violations.
This change is also backwards-compatible with the previous nvme-cli v1.x.
Fixes: #130
=> nvme_metrics.sh: use 'jq -r' for 128-bit "string" numbers

lvm-prom-collector
This pull request add metadata usage metrics to the lvm exporter :
```
node_lvm_thin_pools_allocated{uuid="t2gKmH-8K4K-nwpE-G3CB-DjQS-sjFp-YY7G3L", vgroup="pve"} 55.41
node_lvm_thin_pools_metadata{uuid="t2gKmH-8K4K-nwpE-G3CB-DjQS-sjFp-YY7G3L", vgroup="pve"} 6.37
```
=> lvm-prom-collector: add metadata to the thin metrics

inotify-instances
This is a clear example of why using the official client_python makes much more sense than trying to roll your own metric print function.
=> inotify-instances: use official Prometheus client_python

smartmon.py
This metric is a bit funny, it's a timestamp per device, but it's not accurate enough (seconds, not milliseconds) to derive much useful information from it. This should probably be replaced with a per-device duration metric.
=> Remove smartmon run metric

nvme_metrics.py
This is a Python reimplementation of the existing nvme_metrics.sh script. It features several new metrics:
- nvme_device_info (model, firmware, serial number)
- nvme_physical_size_bytes
- nvme_used_bytes
- nvme_sector_size_bytes
- nvme_unsafe_shutdowns_total
It retains backwards compatibility with the metric names of nvme_metrics.sh with one exception:
The original nvme_critical_warning_total metric is incorrect, because the source is not a counter. The NVMe critical warning field, defined in section 5.16.1.3 of the NVMe Base Specification 2.0c, is a bitmap, and thus should be a gauge in Prometheus. As such, the metric is renamed to simply nvme_critical_warning.
It is my intention that this script should (eventually) supersede and replace the existing `nvme_metrics.sh` script.
=> Add new Python-based nvme_metrics collector

md_info.sh, md_info_detail.sh
1. Skip objects in /dev/md/ which are not block devices (required for CentOS 6)
2. Filter out "/dev/mdXXX:" header line from `mdadm --detail` output, which results in blank label such as `devmdXXX=""`
3. Remove CheckStatus and RebuildStatus label during RAID scrubs/rebuilds (e.g. `CheckStatus="75% complete"`) - fixes #25
=> Fixes to md_info

ipmitool
adding in support for 'percent' as some Fans and other devices (depending on hardware) appear as percentage instead of as a factor of speed.
Signed-off-by: Troy <tmuller@Muller-iMac.local>
=> Update ipmitool with percent

smartmon.py, smartmon.sh
Some versions of smartctl show "Serial number" instead of "Serial Number".  Specifically Ubuntu 20.04.2:
```
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-77-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org
smartctl comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it under
the terms of the GNU General Public License; either
version 2, or (at your option) any later version.
See http://www.gnu.org for further details.
smartmontools release 7.1 dated 2019-12-30 at 15:00:11 UTC
smartmontools SVN rev 5022 dated 2019-12-30 at 15:00:49
smartmontools build host: x86_64-pc-linux-gnu
smartmontools build with: C++14, GCC 9.3.0
smartmontools configure arguments: '--includedir=${prefix}/include' …
```
=> smartmon.sh/smartmon.py: fix serial number collection

mock/fixtures/zfs_list_-p_-H_-t_snapshot_-o_name,used,creation, mock/zfs, zfs-snapshots.py
Generates two metrics for ZFS snapshots:
* zfs_snapshot_space_usage_bytes: snapshot space usage in bytes
* zfs_snapshot_latest_snapshot_taken: UNIX timestamp
=> Add script for ZFS snapshots

lvm-prom-collector
It seems rather inconvenient to have to specify all those switches by hand. Right now, I need to specify `-gpst` to get all the stats and, if some new metric get added (e.g. #159 hopefully), I need to remember to update my callers to match. This is annoying.
Let's make a `-a` that's going to do it all for us. Hell, i'd make it the default, personally, if I wasn't worried about breaking people's stuff...
This obviously conflicts with other PRs that might add another flag like this, like #159. Please prioritize the latter.
=> lvm: add support for "all" checks

storcli.py
SystemExit should be raised, not called
=> fix storcli exporter behavior when storcli is not executable

storcli.py
Old PERC controllers (at least PERC H730/740 Mini) with FW 4.270.00-8168 return BBU status 4096. Comparing the output with MegaCLI output it seems that this bit corresponds to "Learning cycle required" indicator. However since controller runs learning cycles by itself there is no reason for alerting.
=> add "4096" as healthy BBU code

yum.sh
Added the node_reboot_required metric to yum.sh, based on PR #70, with the requested changes incorporated in the code
---
Since PR #70 has been stale for more than 2 years I took the liberty to rewrite it with the changes requested incorporated.
Let me now if this is ok or it needs more work.
=> Add the node_reboot_required metric to yum.sh

apt_info.py
We use the `pkgcache.bin` modification time as a heuristic, but there might be a better way to do this.
We also silently ignore errors when pulling that file to avoid broken systems from breaking the other metrics. I believe this will lead to a null metric which is probably what we want anyway.
A possible improvement to this would be to individually inspect the `InRelease` files and report the mirror's timestamps as well, but that's more involved. It's also not a priority compared to this fix, because we want the update timestamp if we remove the `apt update` run (in #181).
Closes: #180
=> report the apt cache timestamp

apt_info.py
This is causing all sorts of problems. The first of which is that we're hitting our poor mirrors every time the script is ran, which, in the Debian package configuration, is *every 15 minutes* (!!).
The second is that this locks the cache and makes this script needlessly stumble upon a possible regression in APT from Debian bookworm and Ubuntu 22.06:
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/2003851
That still has to be confirmed: it's possible that `apt update` can hang for a long time, but that shouldn't concern us if we delegate this work out of band.
I also do not believe actually performing the `dist-upgrade` calculations is necessary to compute the pending upgrades at all. I've done work with python-apt for other projects and haven't found that to be required: the cache has …
=> do not run apt update or simulate apt dist-upgrade

apt_info.py
As reported in #182, `pkgcache.bin` gets updated on more than just `apt update`. In particular, it gets modified when a package is installed, upgraded or removed.
So let's fallback on a better heuristic, which is the `APT::Periodic` timestamp. This should give us a much more precise and deliberate status.
We also fallback to the `lists` directory, which gets updated when new mirror lists gets moved into place. This does run the risk of staying silently unchanged if there's no change on mirrors but (a) that's rather infrequent and (b) we might actually want to warn on that anyway.
Closes: #183
=> use a better heuristic for the apt update last run time

storcli.py
Adds a new metric under megaraid for physical drives temperature. There's a `Drive Temperature` field under `Drive $DRIVE State`, at least for my controller (PERC H730).
=> Extract drive temperature from storcli

storcli.py
Tested hardware: `LSI SAS3008 PCI-Express Fusion-MPT SAS-3 (rev 02)`
This integrated RAID chip doesn't emit stats for these features.
=> storcli.py: don't error out on unsupported features

btrfs_stats.py
**Performance Improvement:** The regular expression `DEVICE_PATTERN` is precompiled and stored as a function-level variable, ensuring it doesn't need to be recompiled for each iteration in the loop
=> btrfs_stats.py: Precompiled regular expressions improve performance

apt_info.py
Fixes #193 
Fixed `apt_upgrades_pending` always empty, as after #181, `cache.upgrade(True)` is no longer called in script. This call marks the packages that could be upgraded, and without it, no package has the marked_upgrade boolean set to true. Changed to filter all packages that are installed and upgradable. This should match the output of `apt list --upgradable`
Also fixed apt_upgrades_held including all upgradable packages including packages that are not actually held. Package can be detected to be held according to https://askubuntu.com/a/965543.
=> apt_info.py: fix apt_upgrades_pending and apt_upgrades_held

apt_info.py
This is the conventional way and it would allow easier access to the  documentation. See https://peps.python.org/pep-0257/
=> apt_info.py: Uses docstring for module documentation

apt_info.py
Fixes #194 . This implements the fixes as suggested by the issue.
=> Improve heuristic for the apt update last run time

yum.sh
=> lint: format yum.sh

needrestart_info.py
Hi,
I've made a small script to retrieve some metrics from `needrestart`, and perhaps it could be useful for others?
The script runs `needrestart -b` (batch mode), parses the output, and displays some metrics. It looks like this:
```
needrestart_timestamp{version="3.5"} 1.702655157e+09
needrestart_kernel_status{current="5.10.0-26-amd64",expected="5.10.0-26-amd64"} 1.0
needrestart_services_count 0.0
needrestart_containers_count 0.0
needrestart_sessions_count 0.0
```
=> Add needrestart_info.py to monitore needrestart.

smartmon.py, smartmon.sh
Added S.M.A.R.T attribute `percent_lifetime_remain` to smartmon scripts for SSD vendors like Micron/Crucial.
=> smartmon: add percent_lifetime_remain as allowed smart_attribute

smartmon.sh
Removing extra shell command; Use bash builtin for extracting a substring
=> Removing extra shell command; Use bash builtin for extracting a substring

ntpd_metrics.py
The -W 255 parameter ensures that large IPv6 addresses are not truncated when the default 80 column output is used.
=> ntpd_metrics.py: support IPv6 remotes & references

yum.sh
On my OracleLinux 8 and 9 machines, I get unexpected output when a kernel update has been installed but the node has not yet rebooted to run the new kernel. The issue is that "autocheck_running_kernel" is enabled on these machines, and it causes yum/dnf to output things the script doesn't expect. The setting may not be enabled on other systems, but it seems like a sane solution to disable it to force a consistent behaviour regardless of the system-wide settings.
The problem shows itself like this:
```txt
yum_upgrades_pending{origin="is"} 1
yum_upgrades_pending{origin="kernel-core-4.18.0-553.33.1.el8_10.x86_64"} 1
node_reboot_required 1
```
This is because the output is as follows (forcing the setting on to make reproduction easier):
```txt
Security: …
```
=> [yum.sh] Explicitly disable "running kernel"-check

directory-size.sh
#112 removed the referenced `sed` expression.
=> Remove stale comment

smartmon.sh
Allow execution of `smartctl` even if it is installed in an unexpected (for Linux) path.
Some OS, (e.g.: FreeBSD) do not install `smartctl` under the `usr/sbin/` path, but instead use another path like `/usr/local/sbin/`.
This commit makes use of the `which` command to locate the `smartctl` in the `PATH` and execute from there. As such it does not make any assumption where `smartctl` is installed, improving portability.
=> smartmon.sh: locate smartctl tool on non-Linux systems

smartmon.py
No functional changes, just make codespell happy.
=> Spelling fix (makes codespell happy)
